"""crear tablas envios, prueba_entrega y envio_eventos

Revision ID: 54382e256ab0
Revises: 
Create Date: 2026-09-22 08:19:46.296423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54382e256ab0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('origen', sa.String(length=255), nullable=False),
    sa.Column('destino', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_limite_sla', sa.DateTime(timezone=True), nullable=True),
    sa.Column('es_internacional', sa.Boolean(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volumen_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vehiculo_id', sa.UUID(), nullable=True),
    sa.Column('ruta_id', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('envio_eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('envio_id', sa.UUID(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=30), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['envio_id'], ['envios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prueba_entrega',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('envio_id', sa.UUID(), nullable=False),
    sa.Column('url_firma', sa.String(length=500), nullable=True),
    sa.Column('url_foto', sa.String(length=500), nullable=True),
    sa.Column('nombre_receptor', sa.String(length=150), nullable=False),
    sa.Column('entregado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['envio_id'], ['envios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('envio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prueba_entrega')
    op.drop_table('envio_eventos')
    op.drop_table('envios')
    # ### end Alembic commands ###
